### ISSUE TITLE
How to open R in GNU screen window(or a split within that window)

### ISSUE THREAD

**Issue by itissid** [jalvesaq/Nvim-R#147] opened 2017-01-16 18:21 UTC
AFAIU Screen is a terminal emulator like xterm. I run screen it from my Macosx console app and use multiple windows in my screen session. 

How can I start my R session with rf in a new screen window OR?
start it as a split in the same screen window. 

So far I have not been able to achieve this using `let R_term="screen"`. Here is what I tried:
```
let R_vsplit=1
let R_in_buffer=0
let R_applescript=0
let R_tmux_split=0
let R_term='screen'
```

**Comment by itissid** [comment] 2017-01-16 18:21
```
>> vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 15 2016 17:05:53)
MacOS X (unix) version
Compiled by sidharth@sidsoldmacbook.T-mobile.com
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
-cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa  
```

**Comment by jalvesaq** [comment] 2017-01-16 18:38
I know about GNU screen, which is not a terminal emulator, and Nvim-R uses tmux, not GNU screen.
See: https://github.com/ssayols/screenR

**Comment by itissid** [comment] 2017-01-16 19:19
@jalvesaq Thanks for the reply. Seems like that plugin won't work with nvimr(or atleast my current setup). If your answer assumes that that plugin "should" work with nvimr then i ll take my questions there.

**Comment by itissid** [comment] 2017-01-16 19:22
Also since R sessions are started within tmux I was assuming as a workaround I could connect to the tmux from a screen window, but I don't even see the tmux sessions:
```
>> ps -ef|grep tmux
  503 57075     1   0  2:20PM ??         0:00.01 tmux -L NvimR -2 -f /var/folders/1g/1bdx2crd11d516kl0kj429zr0000gq/T/Nvim-R-sidharth/tmux.conf new-session -s NvimR-508 TERM=screen-256color NVIMR_TMPDIR=/var/folders/1g/1bdx2crd11d516kl0kj429zr0000gq/T/Nvim-R-sidharth NVIMR_COMPLDIR=/Users/sidharth/.cache/Nvim-R NVIMR_ID=e8kRJDI9ugkbvxnWkRJntw NVIMR_SECRET=0GezkqeFRIQxXSulkJmS9g R_DEFAULT_PACKAGES=datasets,utils,grDevices,graphics,stats,methods,nvimcom R
  503 57081 32223   0  2:22PM ttys005    0:00.00 grep tmux
  503 57073 57071   0  2:20PM ttys006    0:00.00 tmux -L NvimR -2 -f /var/folders/1g/1bdx2crd11d516kl0kj429zr0000gq/T/Nvim-R-sidharth/tmux.conf new-session -s NvimR-508 TERM=screen-256color NVIMR_TMPDIR=/var/folders/1g/1bdx2crd11d516kl0kj429zr0000gq/T/Nvim-R-sidharth NVIMR_COMPLDIR=/Users/sidharth/.cache/Nvim-R NVIMR_ID=e8kRJDI9ugkbvxnWkRJntw NVIMR_SECRET=0GezkqeFRIQxXSulkJmS9g R_DEFAULT_PACKAGES=datasets,utils,grDevices,graphics,stats,methods,nvimcom R
```
But:
```
>> tmux list-sessions
no server running on /private/tmp/tmux-503/default
14:22:~/exercism/clojure/anagram
```

**Comment by jalvesaq** [comment] 2017-01-16 21:13
The screenR plugin was written for the Vim-R-plugin. So, if it does not work with Nvim-R, this is not a bug.
I used screen in the past, but tmux proved to be better, and it was too time consuming to support both. Then, I dropped the support for screen.
I suggest that you fork screenR and make it work with Nvim-R. Then, you could request that I list your script in the Nvim-R documentation.

**Comment by itissid** [comment] 2017-01-17 01:04
@jalvesaq Thanks. I was able to [hack](https://github.com/jalvesaq/Nvim-R/pull/149/files) my `~/.vim/bundle/Nvim-R/R/common_global.vim` file to get it to sort of work, I only had to add [ten](https://github.com/ssayols/screenR/blob/master/screenR.vim#L121-L127) lines since there was a lot of duplicity. 

A question: If I were to extract that code into a script how would it plugin to NvimR?

**Comment by jalvesaq** [comment] 2017-01-17 01:10
Users interested in the feature would have to put in their vimrc:
```vim
let R_source = "/path/to/your/script.vim"
```

**Comment by jalvesaq** [comment] 2017-02-13 22:49
I am closing the issue. If someone writes the code implementing the requested feature, I will add a link to it in the `R_source` section of Nvim-R documentation.

**Closed** 2017-02-13 22:50 UTC
