### ISSUE TITLE
Nvim-R does not recognize user packages

### ISSUE THREAD

**Issue by bn2302** [jalvesaq/Nvim-R#63] opened 2016-05-17 18:56 UTC
OS: Windows 7x64, R-3.1x64

After installing Nvim-R, I am not able to load packages (via library) installed in the user directory R_LIBS_USER, although the corresponding environment variable has been set. Installing the packages as admin into R_HOME solves the problem, but requires admin rights all the time when installing new packages.

**Comment by jalvesaq** [comment] 2016-05-17 19:10
Were you running Vim as admin when you started R? If yes, then the directory might be owned by the admin.

**Comment by bn2302** [comment] 2016-05-17 19:18
Vim wasn't running with admin rights. I tried to reinstall the missing R packages. They were reinstalled relative to the path of the vim file from which R was spawned, but even loading these (freshly installed packages) failed.

**Comment by jalvesaq** [comment] 2016-05-17 19:34
The plugin was being tested with R-3.2.x on Windows 10 and now it is being tested with R-3.3.0. Please, let me know if you discover that Nvim-R is incompatible with R-3.1.

This might also be relevant to you:
```vim
:h R_set_home_env
```

**Comment by bn2302** [comment] 2016-05-18 20:33
Thanks a lot! Setting R_LIBS_USER did the trick.

**Comment by jalvesaq** [comment] 2016-05-18 21:13
I did not have to set R_LIBS_USER, and users should not be required to do this because the plugin is supposed to work out of the box for users who have Rtools installed. Those who did not install Rtools, have to install the nvimcom binary.

**Comment by galadude** [comment] 2016-09-13 20:23
It's worth emphasizing that the plugin doesn't work with Rtools 3.4, so you should install version 3.3.

**Comment by jalvesaq** [comment] 2016-09-14 09:03
I will add a note in the documentation.

**Comment by jalvesaq** [comment] 2016-10-20 12:17
I am closing the issue. If someone else is experiencing the same issue, and can provide more details on how to reproduce it, the issue should be opened again.

**Closed by jalvesaq** 2016-10-20 12:17 UTC

**Comment by jomuller** [comment] 2018-05-03 10:56
I'm experiencing the same issue and I will provide here more details.

# Bug description

When R is launched with *nvim-r*, my personnal package folder is not available.

*e.g.*: `library(ggplot2)` cause an error message saying the package is not founded.

When I'm using R directly, this is working.

# Probable cause

It tried do dig a little bit and found that the `HOME` environnement variable is not the same in the two cases : 

command | R gui | R launched with nvim-r (r console) |
------------|---|-------------------------|
Sys.getenv('R_LIBS_USER') | "C:\\Users\me/R/win-library/3.5"| "C:\\Users\me\document/R/win-library/3.5"
path.expand('~') | "C:\\Users\me" | "C:\\Users\me\document"
Sys.getenv('HOME') | "C:\\Users\me" | "C:\\Users\me\document"

I checked the value of the HOME environement variable in Windows, it is  "C:\\Users\me".

I cannot figure out why when nvim-r is used, there is another HOME. Because I'm not a Windows poweruser (I don't use windows by choice), I didn't fully understood the notice in the nvimr documentation (:h R_set_home_env) about *The plugin sets `$HOME` as the Windows register value for "Personal" "ShellFolders" which is the same value set by R*. But I believed i'm exactly in this case (I had to set my HOME because by default it was pointing on a network folder). 

# Workaround

Adding `let R_set_home_env = 0` to my *.vimrc*  solved the problem. With this, `path.expand('~')` is `C:\\Users\me`.

# Conclusion

Not a major problem, there is a workaround but make nvim-r not working out of the box.

```r
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0
```

**Comment by jalvesaq** [comment] 2018-05-03 13:40
Is there anything that should be changed in Nvim-R? Is there a way to detect that `$HOME` should not be set?

**Comment by jomuller** [comment] 2018-05-03 15:50
Good question. The initial aim of my comment was only to document further this issue. I don't understand why, in Windows, the HOME is not the same when using directly R and when using nvim-r. If we can understand this, the good behavior should be to use the same HOME in both cases. In other word, why R via nvim-r don't use the same HOME than when we use directly R ?
I have a little knowledge about Windows OS. If you have some clues, I could try to find a way to fix this.
