### ISSUE TITLE
I am getting an object not found after readLines

### ISSUE THREAD

**Issue by dranchalgarg** [jalvesaq/Nvim-R#525] opened 2020-07-27 12:24 UTC

**Comment by jalvesaq** [comment] 2020-07-28 18:15
I need more information to be able to replicate the issue:
What is your operating system?
What version of Nvim-R are you using?
When the error message appears, after what command?

**Comment by dranchalgarg** [comment] 2020-07-31 08:05
> I need more information to be able to replicate the issue:
> What is your operating system?
> What version of Nvim-R are you using?
> When the error message appears, after what command?

Now I am trying to execute the readlines  
df=readLines(con="D:\\analytics\\dataset\\lab2.txt")
df, 

I am getting the following error

function (x, df1, df2, ncp, log = FALSE) 
{
    if (missing(ncp)) 
        .Call(C_df, x, df1, df2, log)
    else .Call(C_dnf, x, df1, df2, ncp, log)
}
<bytecode: 0x000001708ac495c8>
<environment: namespace:stats>

**Comment by jalvesaq** [comment] 2021-04-21 23:17
I'm closing the issue because it doesn't seem to be caused by Nvim-R...

**Closed by jalvesaq** 2021-04-21 23:17 UTC
