### ISSUE TITLE
Installation fails on windows 7

### ISSUE THREAD

**Issue by supersambo** [jalvesaq/Nvim-R#88] opened 2016-07-18 08:18 UTC
Hi,
I'm having some issues trying to install Nvim-R on windows 7. When I try to open a new R console via` ,rf` nvimcom tries to install and fails with the following message

```
* installing to library 'C:/Users/stephan.schloegl/Documents/R/win-library/3.3'
* installing *source* package 'nvimcom' ...
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error in namespaceExport(ns, exports) : 
  undefined exports: nvim.list.args, nvim.srcdir, nvim.plot, nvim.interlace.rnoweb, nvim.interlace.rrst, nvim.print, nvim.names, etags2ctags, nvim.interlace.rmd
Fehler: Laden fehlgeschlagen
Ausführung angehalten
*** arch - x64
Error in namespaceExport(ns, exports) : 
  undefined exports: nvim.list.args, nvim.srcdir, nvim.plot, nvim.interlace.rnoweb, nvim.interlace.rrst, nvim.print, nvim.names, etags2ctags, nvim.interlace.rmd
Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/stephan.schloegl/Documents/R/win-library/3.3/nvimcom'

```
I have installed Rtools (tried 3.3 and 3.4) and I run R 3.2.3. I used pathogen to install Nvim-R and vim version I use was compiled with the following features..

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 10 2016 02:01:08)
MS-Windows 64-bit GUI version mit OLE-Unterstützung
Inklusive der Korrekturen: 1-1829
Übersetzt von micbou <contact@micbou.com>
Riesige Version mit GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl                +cryptv             +find_in_path       +localmap           -postscript         +tag_binary         +viminfo
+arabic             +cscope             +float              +lua/dyn            +printer            +tag_old_static     +vreplace
+autocmd            +cursorbind         +folding            +menu               +profile            -tag_any_white      +wildignore
+balloon_eval       +cursorshape        -footer             +mksession          +python/dyn         +tcl/dyn            +wildmenu
+browse             +dialog_con_gui     +gettext/dyn        +modify_fname       +python3/dyn        -termguicolors      +windows
++builtin_terms     +diff               -hangul_input       +mouse              +quickfix           -tgetent            +writebackup
+byte_offset        +digraphs           +iconv/dyn          +mouseshape         +reltime            -termresponse       -xfontset
+channel            +directx            +insert_expand      +multi_byte_ime/dyn +rightleft          +textobjects        -xim
+cindent            -dnd                +job                +multi_lang         +ruby/dyn           +timers             -xterm_save
+clientserver       -ebcdic             +jumplist           +mzscheme/dyn       +scrollbind         +title              +xpm_w32
+clipboard          +emacs_tags         +keymap             +netbeans_intg      +signs              +toolbar            
+cmdline_compl      +eval               +langmap            +ole                +smartindent        +user_commands      
+cmdline_hist       +ex_extra           +libcall            +packages           +startuptime        +vertsplit          
+cmdline_info       +extra_search       +linebreak          +path_extra         +statusline         +virtualedit        
+comments           +farsi              +lispindent         +perl/dyn           -sun_workshop       +visual             
+conceal            +file_in_path       +listcmds           +persistent_undo    +syntax             +visualextra        

```

Any Ideas what I'm doing wrong?

Btw. thanks for this great plugin which I've been using for years now!

**Comment by songcai** [comment] 2016-07-20 15:55
Try the followings:
    1. Remove any previous nvimcom package in your R.
    2 Make sure your Rtools is installed under C:\Rtools
    3. Open an R console, change the working directory (using setwd) to the R directory under the Nvim-R plugin folder (will be something like ...Nvim-R/R/)
    4. Within R, run
        install.packages("./nvimcom", type="source", repos=NULL)

Will the above procedure solve your problem?

Song

**Comment by songcai** [comment] 2016-07-20 16:01
Jakson,

Are you still using "R CMD INSTALL nvimcom_version_number.tar.gz" to install nvimcom? If so, supersambo should not have this problem. I guess you changed something?

With the newest Nvim-R, I am getting a similar architecture error when installing nvimcom from within Nvim-R. But if I manually install the nvimcom coming with Nvim-R using R CMD install (or the procedure I outlined in the above post), everything went perfectly fine.

Cheers,
Song

**Comment by jalvesaq** [comment] 2016-07-20 16:14
The commands to build nvimcom are the following:

```
cd [NVIMR_TMPDIR]
R CMD build "[NvimR home]/R/nvimcom"
R CMD INSTALL nvimcom_[version number].tar.gz
```

That is, Nvim-R builds the nvimcom .tar.gz package in its temporary directory and, then, installs the package.

**Comment by songcai** [comment] 2016-07-20 16:20
I opened an separate report

**Comment by supersambo** [comment] 2016-07-21 11:28
Thanks for your reply. Installing the package manually from the console solved the issues!

**Comment by songcai** [comment] 2016-07-21 13:22
That is good to know. However,  Jakson's way of compiling nvimcom looks perfect to me. Maybe the tmp folder is doing something to interfere the compiling process?

**Comment by jalvesaq** [comment] 2016-07-21 16:42
Perhaps there is more than one version of R installed... Putting this in the .Rprofile could be helpful to diagnostic the problem:
```
print(version)
```

**Comment by songcai** [comment] 2016-07-26 14:44
supersambo: Did you install both x64 and i386 files? If you did not, please try install R files for both architectures. Second, make sure you add the path for Rtools (for example, R:\Rtools\bin and R:\Rtools\gcc-4.6.3\bin) to Windows PATH environment variable..

**Comment by jalvesaq** [comment] 2016-07-31 00:00
The installation of both 32 and 64 bit files should no longer be required: https://github.com/jalvesaq/Nvim-R/commit/9966dbb800983b7ed24c9087d6ccd62db79db030

**Comment by jalvesaq** [comment] 2016-08-06 10:58
I will close this issue soon because I cannot reproduce the bug.

**Closed** 2016-08-07 15:38 UTC
