### ISSUE TITLE
RHelp in preview window

### ISSUE THREAD

**Issue by zippeurfou** [jalvesaq/Nvim-R#206] opened 2017-06-11 14:01 UTC
In a perfect world, I'd love to be able to see the help in the preview windows (the same as when you press `\rh`) and the arguments in the status line (which is already possible). This would mimic the behavior of other languages that omnicompletion do in my setup.
I can't see how to show the help in the preview window which would be so much appreciated.
If someone can guide me what work would be required, I'd gladly try to do a PR.

**Comment by jalvesaq** [comment] 2017-06-14 18:42
The pop up menu of omnicompletion has an option for setting the contents of a preview window. We can put anything in the preview window, but it does not have syntax highlight. Currently, the preview window only shows the function's arguments (see `:h R_show_args`). We could add more information to the preview window if there was a function to retrieve that info. For example, we can use `packageDescription()` to get information on packages, but I'm not aware of a function that could get information on functions.

**Comment by zippeurfou** [comment] 2017-06-14 19:02
isn't `?NameOfFunction` and `help(NameOfFunction)` returns information on functions?
`help` also output the `packageDescription()`.

**Comment by jalvesaq** [comment] 2017-06-14 21:10
Yes, `?` and `help()` return information on functions, but with two problems:
- The text is difficult to parse to extract specific information.
- Some functions share the same documentation, and not all functions documented in the same file have the same arguments. Example: `?read.csv`.

**Comment by zippeurfou** [comment] 2017-06-14 21:36
I see the issue. You'd have to do lot of works to have something that makes sense. 
I am not sure there is a best answer. Doing a grep of the Usage column that start with the function name and of the arguments part with the correct argument not only would be hard but most likely slow as well.

**Comment by zippeurfou** [comment] 2017-06-22 17:49
Have you looked at the [gbRd](https://cran.r-project.org/web/packages/gbRd/gbRd.pdf) package?
It has a lot of handy function that could do the job combined with `formalArgs`.
There are definitely different way you could go depending what you want to output.
For example here is a neat way to get more from the args:
```
cat(Rdo_args2txt("read.csv",formalArgs(read.csv)))
```
If you want to get the description you can do as follow:
```
Rd_help2txt("read.csv",keep_section="\\description",omit_sec_header=TRUE)
```

**Comment by jalvesaq** [comment] 2017-06-25 21:57
I did not know about the gbRd package. Thanks for finding it!
Could you, please, try the [args_info](https://github.com/jalvesaq/Nvim-R/tree/args_info) branch?

**Comment by zippeurfou** [comment] 2017-06-26 05:09
Hi @jalvesaq, the argument completion works like a charm! This is really awesome.
I am using: https://github.com/jalvesaq/Nvim-R/commit/53a3d83fe7d79d0be8adef57e2d581e495027f1b.
Sad to read that gbRd has issue with speed :(
Some observations:
The next screenshots have the preview as well as the help for comparaison.
As you mentioned in the commit message not everything get extracted. It's hard to tell if there is a "good" solution for it. I will keep looking.
Theses 2 screenshot show some tags not removed:
<img width="696" alt="screen shot 2017-06-26 at 12 45 57 am" src="https://user-images.githubusercontent.com/4520383/27525107-fab6b9b2-5a08-11e7-9ca8-072ac8dd01a2.png">
<img width="868" alt="screen shot 2017-06-26 at 12 44 54 am" src="https://user-images.githubusercontent.com/4520383/27525109-faba4474-5a08-11e7-8c87-8201c1e24421.png">

The next two screenshot are for suggestions. It works fine but there might be a better way to display it:
<img width="870" alt="screen shot 2017-06-26 at 12 43 00 am" src="https://user-images.githubusercontent.com/4520383/27525110-fabdfa38-5a08-11e7-8a81-08b0a417578e.png">
As you can see if there are lot of arguments it can be a bit hard to "read". The R help as a nice way to break it inside a new line. It could be nice to have the same.

<img width="867" alt="screen shot 2017-06-26 at 12 40 20 am" src="https://user-images.githubusercontent.com/4520383/27525108-faba2de0-5a08-11e7-9be8-b06ada4059ad.png">

Here, I wonder if we should not try to have some indentation a bit similar as the help.
It is a bit hard to read/find the usage and description.
It might be nice to have the formatting for the description follow the same pattern with `Description:` new line indented (5 spaces) with content of description and `Usage:` and same thing.
I also wonder if the title should also be included as on this example the description without the title make it hard to understand in my opinion.

Lastly, the leading spaces on the arguments differs that is very slightly disturbing (try with `rnorm` you will see it, my screenshot might be hard to see but there is 7 leading space for n and only 3 for mean). Maybe just deleting them would be enough.
<img width="381" alt="screen shot 2017-06-26 at 1 04 44 am" src="https://user-images.githubusercontent.com/4520383/27525398-8a7e9c98-5a0b-11e7-8c94-960d9800cc24.png">
<img width="627" alt="screen shot 2017-06-26 at 1 04 34 am" src="https://user-images.githubusercontent.com/4520383/27525399-8a7ed7f8-5a0b-11e7-8923-99c1ebea54d1.png">

**Comment by jalvesaq** [comment] 2017-06-26 14:29
I improved the cleaning of function descriptions. I will try to improve more things later this week.

**Comment by zippeurfou** [comment] 2017-06-26 17:45
Here are two different alternatives:
1. Inspired by Rstudio [source code](https://github.com/rstudio/rstudio/blob/54cd3abcfc58837b433464c793fe9b03a87f0bb4/src/cpp/session/modules/SessionHelp.R#L402): Use the html help and parse the tags. Might be easier to parse.
2. Use built in R function and then do some manually parsing. 
```
elem <- capture.output(tools::Rd2txt(utils:::.getHelpFile(help("rnorm"))))
```
And then if you want to have the description parse within: `"_\bD_\be_\bs_\bc_\br_\bi_\bp_\bt_\bi_\bo_\bn:"` and whatever that start with `"_\b`.
You could also create another environment and use `tools::Rd2txt_options(underline_titles=F)` and then just parse the section by keywords (i.e. match anything that start with a new line with Description and finish with a new line with any other tag name).

A quick note: looking at [rstudio source code](https://github.com/rstudio/rstudio/blob/54cd3abcfc58837b433464c793fe9b03a87f0bb4/src/cpp/session/modules/SessionHelp.R#L98)  I found an interesting function which is:
```
>   sort(utils:::matchAvailableTopics("","rn"))
[1] "rnbinom" "rnchisq" "rnorm"
```
I am not sure what logic you are using under the hood but it seems to be quite a clean way to do it.

**Comment by jalvesaq** [comment] 2017-06-26 18:15
The completions of omni completion are cached when the package is either loaded for the first time or loaded after an upgrade. I would have to call `Rd2txt` for each function (1245 times for the package `base` which would take more than 10 seconds in my laptop). The function `tools:::fetchRdDB` is much faster because it retrieves the whole documentation of a package at once.

**Comment by jalvesaq** [comment] 2017-06-26 18:31
HTML is not so easy to parse. It is much easier to use `Rd2txt`. But when I try to complete `p` I get 172 suggestions of completion, and calling Rd2txt 172 times might be slow.

**Comment by zippeurfou** [comment] 2017-06-26 20:41
I see, thank you for your feedback. I will look if there is a way to just take part of `Rd2txt` to have something better while still being ok speed wise.

**Comment by jalvesaq** [comment] 2017-06-27 01:43
If you will try to improve the code, please, run this before and after your changes to see how they affect the speed:
```r
system.time(nvimcom:::nvim.bol("/tmp/omnils_base_", "base", TRUE))
```

**Comment by jalvesaq** [comment] 2017-06-27 13:09
@zippeurfou I was trying to highlight `Description:` and `Usage:` as `Title`, but I couldn't.
Do you know any plugin that highlights the contents of the preview window displayed during omni completion?

**Comment by zippeurfou** [comment] 2017-06-28 17:29
@jalvesaq I am not exactly sure. I think it just act as a normal buffer.
i.e. doing `:set syntax=r`
I got this result:
![screen shot 2017-06-28 at 1 28 39 pm](https://user-images.githubusercontent.com/4520383/27651273-bcda66bc-5c05-11e7-90dd-12136ecd271c.png)

**Comment by jalvesaq** [comment] 2017-06-28 18:07
The problem is that when I tried to do this automatically the script window (not the preview) got the syntax highlight.

**Comment by zippeurfou** [comment] 2017-06-28 19:33
Did you try: `:autocmd! BufWinEnter * if &previewwindow | set filetype=r| endif` ?

**Comment by jalvesaq** [comment] 2017-06-28 21:58
The problem is that Nvim-R will not be the only plugin to use a preview window. For example, we can use omni completion for C:
```
autocmd Filetype c setlocal omnifunc=ccomplete#Complete
```

**Comment by jalvesaq** [comment] 2017-06-28 22:46
I'm trying to fix the issue with a variable created by the completion function...

**Comment by jalvesaq** [comment] 2017-06-28 23:20
The syntax highlighting of the preview window should be working now. You might have to start R, close R and (Neo)Vim, and open it again to completely clean the cache because there was a minor change in the format of the info (I replaced `\n` with `\N`).

**Comment by zippeurfou** [comment] 2017-06-29 00:06
Wow this is really awesome!
I was going to use something like:

```
autocmd BufRead,BufNewFile *  if &filetype==r | let g:mysynt = 1 | else | let g:mysynt = 0 | endif
autocmd BufWinEnter * if &previewwindow && g:mysynt | let &filetype = rdoc | endif
```
However I believe your solution is better.
I have noted some "bug" with escaping `\`.
Here are two examples:
<img width="1096" alt="screen shot 2017-06-28 at 7 57 53 pm" src="https://user-images.githubusercontent.com/4520383/27665756-2099bf54-5c3d-11e7-8d33-6a26a97f6b64.png">
<img width="1426" alt="screen shot 2017-06-28 at 7 57 21 pm" src="https://user-images.githubusercontent.com/4520383/27665757-209f89b6-5c3d-11e7-8664-ab74c08b1728.png">

**Comment by jalvesaq** [comment] 2017-06-29 01:11
The bug was due to not escaping `"`. It's fixed now.

**Comment by jalvesaq** [comment] 2017-06-29 15:58
The omni completion now inserts line breaks in long `Usage` lines.

**Comment by jalvesaq** [comment] 2017-07-02 19:34
I'm going to merge the branch. If still there is any issue we will fix it later.

**Closed** 2017-07-02 19:35 UTC

**Comment by zippeurfou** [comment] 2017-07-03 01:31
Big thanks for the support. It looks really awesome to use it.

**Comment by jalvesaq** [comment] 2017-07-03 02:13
Thanks for your help.
