### ISSUE TITLE
Error detected while processing function ROnJobStdout

### ISSUE THREAD

**Issue by idavydov** [jalvesaq/Nvim-R#784] opened 2023-12-14 17:05 UTC
I have a fairly complicated code, which brings nvim-r in the state where `RAction("print")` causes the following error:
```
Error detected while processing function ROnJobStdout:
line   40:
E115: Missing quote: 'cfb_line_plt <some function names> hpl$plot[[1]]@ht_list$matrix_9@matrix_color_mapping@col_fun hpl$plot[[1]]@ht_list$matrix_10@matrix_color_mapping@col_fun hpl$plot[[2]]@ht_list$matrix_11@matrix_color_mapping@col_fun hpl$plot[[2]]@ht_list$matrix_12@matrix_color_mapping@col_fun hpl$plot[[3]]@ht_list$matrix_13@matrix_color_mapping@col_fun hpl$plot[[3]]@ht_list$matrix_14@matrix_color_mapping@col_fun hpl$plot[[4]]@ht_list$matrix_15@matrix_color_mapping@col_fun hpl$plot[[4]]@ht_list$matrix_16@matrix_color_mapping@col_fun hpl$plot[[5]]@ht_list$matrix_17@matrix_color_mapping@col_fun hpl$plot[[5]]@ht_list$matrix_18@matrix_color_mapping@col_fun hpl$plot[[6]]@ht_list$matrix_19@matrix_color_mapping@col_fun hpl$plot[[6]]@ht_list$matrix_20@matrix_color_mapping@col_fun hpl$plot[[7]]@ht_list$matrix_21@matrix_color_mapping@col_fun hpl$plot[[7]]@ht_list$matrix_22@m
Error detected while processing function ROnJobStdout:
line   40:
E116: Invalid arguments for function UpdateLocalFunctions
[Server] Unknown command: eft_annotation@anno_list$part@color_mapping@col_fun obs_hm_plots$hm[[8]]@left_annotation@anno_list$part@fun@fun paird_plt pd_hea [...]
```

I managed to simplify it to 177 lines, but it's still quite complex and has an internal functions which I cannot seem to easily remove without affecting reproducibility of the error.

The code ends with the following lines:
```
hpl <- tibble(1:10) |>
  rowwise() |>
  mutate(
    plot = list(
      ComplexHeatmap::Heatmap(matrix(rnorm(100), nrow = 10)) +
        ComplexHeatmap::Heatmap(matrix(rnorm(100), nrow = 10))
    )
  )
```

`:RDebugView` doesn't seem to show anything suspicious.

Would you have any suggestions on how can I debug this?

**Comment by jalvesaq** [comment] 2023-12-14 18:55
`RAction("print")` is triggered by `<LocalLeader>rp`. So, I need a sample code to replicate the issue and instructions on what object the cursor should be over when I press `<LocalLeader>rp`. You can send the code and, if necessary, an `RData` file to jalvesaq (at) gmail dot com.

**Comment by idavydov** [comment] 2023-12-15 11:26
I now have doubts that this could be reproduced in another environment.

E.g., if I disable renv, the error (sometimes) disappears; I am not able to replicate it on Mac OS (only linux). The code also reads some files from remote, and I think the error could be timing sensitive (the more statements I remove, the less likely the error appears).

It seems it has something to do with input parsing (?)

E.g., once when trying with another version of R, I saw the following after the startup:

```
Cannot start R: nvimrserver not running
Error detected while processing function RInitStdout:
line   28:
E492: Not an editor command:  gcc -I"/apps/rocs/2020.08/cascadelake/software/R/4.2.2-foss-2020a/lib64/R/include" -DNDEBUG   -I/apps/rocs/2020.08/cascadelake/software/MariaDB/10.6.4-GCC-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/netCDF/4.7.4-gompi-2020a/include -I/apps/rocs/2020.08/cascadelake/software/ImageMagick/7.0.10-1-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/libsodium/1.0.18-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/cyrus-sasl/2.1.27-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/UDUNITS/2.2.26-foss-2020a/include -I/apps/rocs/2020.08/cascadelake/software/nodejs/13.12.0-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/HDF5/1.10.6-gompi-2020a/include -I/apps/rocs/2020.08/cascadelake/software/PCRE2/10.34-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/XZ/5.2.5-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/NLopt/2.6.1-GCCcore-9.3.0/include -I/apps/rocs/2020.08/cascadelake/software/X1
```

Is there maybe a way to enable debug output so I could see the input it breaks on?

**Comment by jalvesaq** [comment] 2023-12-15 14:10
I have never used `renv`... But, please, read:
  - the section _The communication between R and either Vim or Neovim_ at the end of the [README.md](https://github.com/jalvesaq/Nvim-R/blob/master/README.md);
  - [remote_access.md](https://github.com/jalvesaq/Nvim-R/blob/master/doc/remote_access.md).
 
R and Vim/Neovim must be in the same machine/environment. If they are not, some environment variables must be adjusted, otherwise, the communication between Vim/Neovim and R will not work. In this case, this plugin will be useless and you will be better off using [vimcmdline](https://github.com/jalvesaq/vimcmdline). Maybe you can adjust the instructions to remote access through `ssh` to your case (running R in one environment and Neovim in another).

**Comment by idavydov** [comment] 2023-12-15 16:06
Thanks a lot, @jalvesaq . I just managed to create an example without `renv` which breaks most of the time.

It still only runs in a certain environment, but with different versions of R.

Any suggestions on how to proceed?

**Comment by jalvesaq** [comment] 2023-12-15 16:11
You can either post the example here or send the code by email. But I guess that the problem is caused by different versions of nvimcom (Nvim-R source _vs_ nvimcom installed by a previous version of Nvim-R). There are two ways of fixing the mismatch: exclude the nvimcom package from being frozen or downgrade Nvim-R.

**Comment by idavydov** [comment] 2023-12-15 17:24
Here's the current code after multiple minimization attempts. Apologies, it's quite messy, but removing more parts usually stops the problem from reproducing. Currently it  breaks nvim-r 80% of the time.

I basically have to open nvim + nvim-r, press `<localleader>rf` to start R, `<localleader>aa` to execute and then `<localleader>rp` on a couple of different symbols.

<details>
<summary>the code</summary>

```
library(tidyverse)

cc <- readRDS("cc.Rds")

obs_hm <- function(d, tt) {
  m <- select(d, -PT, -PART) |>
    as.matrix()

  ComplexHeatmap::Heatmap(
    m,
    col = c("0" = "white", "1" = "blue"),
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    show_heatmap_legend = FALSE,
    left_annotation = ComplexHeatmap::rowAnnotation(
      part = d$PART,
      col = list(part = c("I" = "brown", "II" = "cyan"))
    ),
    column_title = tt
  )
}

obs_hm_plots <- cc |>
  distinct(PART, USUBJID, UVISIT, PARAM) |>
  arrange(UVISIT) |>
  mutate(present = 1) |>
  pivot_wider(names_from = UVISIT, values_from = present, values_fill = 0) |>
  mutate(PT = str_replace(USUBJID, "[^-]+-", "")) |>
  select(PT, everything()) |>
  select(-USUBJID) |>
  arrange(PART, PT, PARAM) |>
  group_by(PARAM) |>
  nest() |>
  mutate(
    hm = map(data, obs_hm, PARAM)
  )


w <- function(...) {
  data.frame(
    pvalue = rnorm(1),
    coef = rnorm(1),
    sd = rnorm(1),
    model = "hi"
  )
}

f <- function(dat) {
  tbllist <- dat %>%
    dplyr::group_by(PARAM, UVISIT) %>%
    tidyr::nest(aaa = -dplyr::group_cols()) %>%
    dplyr::mutate(results = purrr::map(aaa, \(x) w(
    ))) %>%
    dplyr::ungroup()
  results <- tbllist %>%
    dplyr::select(PARAM, UVISIT, results) %>%
    tidyr::unnest(results)
  results %<>%
    dplyr::group_by(UVISIT) %>%
    dplyr::mutate(pvalue_adj = stats::p.adjust(pvalue, method = "fdr")) %>%
    dplyr::ungroup()
  datalist <- tbllist %>% dplyr::select(PARAM, UVISIT, aaa)
  out <- list(results = results, datalist = datalist)
  class(out) <- c("list", "hd")
  return(out)
}


rt <- cc |>
  f()


hpl <- tibble(1:10) |>
  rowwise() |>
  mutate(
    plot = list(
      ComplexHeatmap::Heatmap(matrix(rnorm(100), nrow = 10)) +
        ComplexHeatmap::Heatmap(matrix(rnorm(100), nrow = 10))
    )
  )
```

</details>

I can share the `cc.Rds`, but would it really be helpful if I cannot reproduce it on a different machine?

**Comment by idavydov** [comment] 2023-12-15 17:34
And just to clarify, this now breaks w/o renv (in a clean folder), so I doubt it has anything to do with nvimcom version conflict.

**Comment by jalvesaq** [comment] 2023-12-15 21:41
Rarely I'm able to fix a bug without being able to replicate it. So, I need the `cc.Rds` file. I don't need to understand your code. I will just run it and do `<LocalLeader>rp` over some objects. So, could you, please, send the file by e-mail?

**Comment by idavydov** [comment] 2023-12-18 12:37
I just shared the file via email (as a gzipped csv). So the code to read the file would be (updated in the comment as well):

```
cc <- read_csv("cc.csv")
```

I am hoping you'd be able to reproduce it, but if not, I'm happy to hear how can I debug it locally.

**Comment by jalvesaq** [comment] 2023-12-18 13:28
I ran the code and did `<LocalLeader>rp` on top-level objects, but didn't see the bug.

I usually start debugging with `grep -R something` in the Nvim-R directory, where `something` is part of the error message. Doing this now, I can replicate the "Invalid arguments for function UpdateLocalFunctions" error with the following code:

```r
`aa'bb` <- function(x) x + 1
```

**Comment by idavydov** [comment] 2023-12-19 08:16
I just tried the `manyfun` branch. And I was unable to reproduce the error anymore. Tried several times, including the real code which broke previously.


Thank you so much!

**Comment by klmr** [comment] 2023-12-19 08:23
@jalvesaq 

> because nobody will put single quotes in the names of objects (at least, I hope so)

Unfortunately I am pretty sure I have encountered this: column names of tables imported from files will occasionally contain all kinds of characters, and apostrophes (= single quotes) are amongst them. And there are many ways in which column names will be used as actual R object names (e.g. when accessing them inside ‘dplyr’ verbs or via the `$` subset operator, or when attaching the table).

**Comment by idavydov** [comment] 2023-12-19 08:33
@klmr 
I just tried the following code:
```
x <- tibble::tibble(1:10, `aa'bb` = 1:10)
print(x)
#> # A tibble: 10 × 2
#>    `1:10` `aa'bb`
#>     <int>   <int>
#>  1      1       1
#>  2      2       2
#>  3      3       3
#>  4      4       4
#>  5      5       5
#>  6      6       6
#>  7      7       7
#>  8      8       8
#>  9      9       9
#> 10     10      10
```

I do not think it breaks anything (unlike ``` `aa'bb` <- function(x) x + 1 ```).

**Comment by jalvesaq** [comment] 2023-12-19 13:35
The completion issue is fixed now on the manyfun branch.

**Comment by idavydov** [comment] 2023-12-20 09:57
I briefly tested the current `manyfun` version. It seems to work well, however autocomplete is not escaping symbols.

E.g., `x$` from the example above will be autocompleted to `x$1:10`, while it should be `` x$`1:10` ``, I think.

I understand that it's quite complex to implement proper symbol escaping and this is not an issue at all for me. Just letting you know in case you find this important.

**Comment by jalvesaq** [comment] 2023-12-20 11:08
Thanks for testing it! I knew that, ideally, it should escape names that require backticks quoting, but, indeed, I would lose too much time to implement it, and very few people would benefit from it. The workaround is simple: don't use names that require backtick quotes or change the ones that do require them. Anyway, if someone wants to fix it, the files to be edited are `R/complete.vim` (for omni completion) and `lua/cmp_nvim_r/init.lua` (at [cmp-nvim-r](https://github.com/jalvesaq/cmp-nvim-r), for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)).

**Closed** 2023-12-20 21:20 UTC

**Comment by micha-silver** [comment] 2024-03-12 11:23
I'm getting a similar error right at startup of nvim when I try to edit any *.R file:

 ```                                                                                                                                                           
Error detected while processing function ROnJobStdout[40]..UpdateSynRhlist[11]..FunHiOtherBf:
line   11:
E5555: API call: Invalid key: 'buf'
Press ENTER or type command to continue
```
Any suggestions how to debug this, and find a solution?
I'm using Debian 12, with the packaged version of neovim:
```
micha@RMS:~$ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org
```
and a recent version of R:
```
micha@RMS:~$ R --version
R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"
```
Thanks

**Comment by jalvesaq** [comment] 2024-03-12 11:42
@micha-silver, can you see the documentation for `nvim_set_option_value`? That is, what do you see after `:help nvim_set_option_value`? On recent Neovim versions, the documentation is:

```
                                                     *nvim_set_option_value()*
nvim_set_option_value({name}, {value}, {opts})
    Sets the value of an option. The behavior of this function matches that of
    |:set|: for global-local options, both the global and local value are set
    unless otherwise specified with {scope}.

    Note the options {win} and {buf} cannot be used together.

    Parameters: ~
      • {name}   Option name
      • {value}  New option value
      • {opts}   Optional parameters
                 • scope: One of "global" or "local". Analogous to
                   |:setglobal| and |:setlocal|, respectively.
                 • win: |window-ID|. Used for setting window local option.
                 • buf: Buffer number. Used for setting buffer local option.
```

If the function `nvim_set_option_value()` isn't available for Neovim 0.7.2, I will make Nvim-R call the alternative function `nvim_buf_set_option()`, which is deprecated now.

**Comment by micha-silver** [comment] 2024-03-12 11:50
Yes, here's what I see:
```

                                                     nvim_set_option_value()
nvim_set_option_value({name}, {value}, {*opts})
                Sets the value of an option. The behavior of this function
                matches that of :set: for global-local options, both the
                global and local value are set unless otherwise specified with
                {scope}.

                Parameters:
                    {name}   Option name
                    {value}  New option value
                    {opts}   Optional parameters
                             • scope: One of 'global' or 'local'. Analogous to
                               :setglobal and :setlocal, respectively.

```

**Comment by jalvesaq** [comment] 2024-03-12 12:11
So, Neovim 0.7.2 has the function, but its `opts` argument doesn't have the `buf` key... I increased the requirement to use the function to Neovim 0.8.0 (not knowing if 0.8.0 actually has the key in the options dictionary) . Is it working for you now?
