### ISSUE TITLE
Vim: Caught deadly signal SEGV

### ISSUE THREAD

**Issue by lucasfariaslf** [jalvesaq/Nvim-R#56] opened 2016-04-11 05:37 UTC
I've just installed nvim-r. To check if it's working fine, i created an example script file with a simple R command. I then started R (`\rc`) and ran the line. The command was executed fine, but some seconds after I received the message:

```
Vim: Caught deadly signal SEGV
Vim: preserving files...
Vim: Finished.
Segmentation fault (core dumped)
```

Tried with some other scripts i have, happened the same. 

My first guess was to come here and check the closed and opened issues, found nothing. Over the web ti says it can be caused by a number of reasons, including hardware, which i doubt, or vim itself. But since it doesn't happen with other plugins or vim alone, I thought I should come here and see if you guys can help me.

**Comment by jalvesaq** [comment] 2016-04-11 09:44
I can't reproduce the bug. What is your operating system? What is your vim version? And what are the parameters that you pass to R (since you are starting R with `\rc` and not `\rf`)?

**Comment by lucasfariaslf** [comment] 2016-04-11 11:48
Thank you for the quick reply, Jackson. Just after you mentioning I realized I was using the wrong shortcut. The problem didnt happen using `\rf`. I sincerely apologize for my oversight.

**Comment by jalvesaq** [comment] 2016-04-11 12:46
Vim should never crash. Regardless of what plugins you have installed, errors should never cause a crash. I could not reproduce the bug in Vim (terminal), but now I can reproduce the bug with `\rf` in GVim. The bug seems to be related with garbage collection. I have got the following gdb backtrace:

```
#0  0x00000000004419d8 in set_ref_in_item (tv=0xf5a9e0, copyID=126, ht_stack=0x7fffffffce48, list_stack=0x0) at eval.c:7357
#1  0x0000000000441490 in set_ref_in_ht (ht=0x8bc910 <globvardict+16>, copyID=126, list_stack=0x0) at eval.c:7173
#2  0x00000000004410ba in garbage_collect () at eval.c:6983
#3  0x00000000004b7efe in before_blocking () at getchar.c:1526
#4  0x00000000005f8eb4 in gui_wait_for_chars (wtime=-1) at gui.c:2953
#5  0x00000000005dd880 in ui_inchar (buf=0x12cd5b2 "", maxlen=52, wtime=-1, tb_change_cnt=328) at ui.c:186
#6  0x00000000004ba45c in inchar (buf=0x12cd5b2 "", maxlen=157, wait_time=-1, tb_change_cnt=328) at getchar.c:3056
#7  0x00000000004ba026 in vgetorpeek (advance=1) at getchar.c:2832
#8  0x00000000004b8056 in vgetc () at getchar.c:1605
#9  0x00000000004b859a in safe_vgetc () at getchar.c:1801
#10 0x000000000050afbc in normal_cmd (oap=0x7fffffffd2d0, toplevel=1) at normal.c:627
#11 0x000000000062097c in main_loop (cmdwin=0, noexmode=0) at main.c:1359
#12 0x0000000000620293 in main (argc=4, argv=0x7fffffffd5e8) at main.c:1051
```

**Comment by jalvesaq** [comment] 2016-04-11 19:28
It seems that the bug is fixed in Vim 7.4.1722.

**Comment by lucasfariaslf** [comment] 2016-04-12 08:20
This version doesn't seem to be in the official repository yet, but i'll have it installed anyway. Thank you again sir!

**Comment by jalvesaq** [comment] 2016-04-12 08:53
The official Vim repository is https://github.com/vim/vim

**Closed** 2016-04-13 01:18 UTC
