### ISSUE TITLE
Errors with formatting with dplyr syntax (%>%)

### ISSUE THREAD

**Issue by calenwalshe** [jalvesaq/Nvim-R#186] opened 2017-04-21 18:01 UTC
Is there something that I can do to ensure that formatting (indenting) code '=' will perform correct when I have syntax that includes dplyr code? Currently the formatter does unexpected things such as improperly intending code when I have dplyr syntax.

**Comment by jalvesaq** [comment] 2017-04-21 18:43
You may try to set the value of `g:r_indent_op_pattern` in your vimrc. Currently, its default value is:
```
'\(&\||\|+\|-\|\*\|/\|=\|\~\|%\|->\)\s*$'
```

**Comment by jalvesaq** [comment] 2017-04-25 01:27
Please, see https://github.com/jcfaria/Vim-R-plugin/issues/160

**Comment by calenwalshe** [comment] 2017-04-25 02:06
Thanks for the information, this is helpful. Also, the R package formatR works as an alternative.

**Comment by jalvesaq** [comment] 2017-04-25 03:20
It is good to know that there is an alternative. It would be even better if someone wrote a better `indent/r.vim` script. But this is not easy because it would have to correctly indent the first 604 lines of https://github.com/jalvesaq/R-Vim-runtime/blob/master/tests/indent_test.R

**Comment by tvatter** [comment] 2019-03-08 20:15
I noticed a similar issue. Look at the following result of the formatting:
```
library(keras)
input <- layer_input(shape = 2)
output1 <- input %>%
  layer_dense(units = 10, input_shape = 2) %>% 
  layer_dense(units = 10, input_shape = 2)

output2 <- input %>%
  layer_dense(units = 10, 
              input_shape = 2) %>% 
layer_dense(units = 10, 
            input_shape = 2) 

output3 <- input %>%
  layer_dense(units = 10, activation = 'relu') %>% 
  layer_dense(units = 10, activation = 'relu') 

output4 <- input %>%
  layer_dense(units = 10, 
              activation = 'relu') %>% 
layer_dense(units = 10, 
            activation = 'relu') 
```
As you can see, there is something weird going on with the indentation of the second layers for outputs 2 and 4. Apologies about using keras, but I wasn't able to produce an MWE:
```
library(dplyr)
library(nycflights13)
flights %>%
  group_by(year, month, day) %>%
  mutate(year = arr_delay, tot_delay = arr_delay + dep_delay) %>% 
  mutate(year = arr_delay, tot_delay = arr_delay + dep_delay)

flights %>%
  group_by(year, month, day) %>%
  mutate(year = arr_delay, 
         tot_delay = arr_delay + dep_delay) %>% 
  mutate(year = arr_delay, 
         tot_delay = arr_delay + dep_delay)
```
Here, the indentation appears to be correct.

Any idea what is going on?

**Comment by tvatter** [comment] 2019-03-08 20:38
Another one that does not work as expected:
```
delay  <- flights %>% 
select(arr_delay, dep_delay) %>% 
as.matrix()

    if (something) {
      delay  <-  delay + 1 
    }
```

**Comment by jalvesaq** [comment] 2019-03-09 15:30
Running `:debug call GetRIndent()` on both the wrongly indented `layer_dense` line and the correctly indented `mutate` line, I see that in both cases the operators were ignored because the parentheses were not balanced in the previous line and other rules were used to indent the lines. It was only by coincidence that one is wrongly indented and the other is correctly indented.

**Comment by tvatter** [comment] 2019-03-09 19:22
I see. You mean that the indentation algorithm currently can't handle parentheses that are balanced over multiple lines? In both cases, there is a line break because it is often convenient to spread arguments over multiple lines when a given function's calls require many arguments.

**Comment by jalvesaq** [comment] 2019-03-09 19:31
Yes, but the problem is only with the dplyr syntax. Ordinary R code is correctly aligned.

I may eventually try to rewrite the indent/r.vim script to fix this and other issues. But, this is not going to happen soon.

**Comment by tvatter** [comment] 2019-03-09 19:49
Ok, understood, thanks for the explanations.

**Comment by jalvesaq** [comment] 2024-02-18 15:39
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).

**Closed by jalvesaq** 2024-02-18 15:39 UTC
