### ISSUE TITLE
Manually killing pdf viewer prevents vim from opening it again

### ISSUE THREAD

**Issue by Unaimend** [jalvesaq/Nvim-R#786] opened 2023-12-17 19:15 UTC
Hi,

When I knit a document to pdf it automatically opens my pdf viewer as expected. 
Setting `let R_openpdf = 1` also results in a correct update of the window when I DONT close it manually. But in the case where I **manually** close zathura THEN switch back to nvim and re-execute the pdf Zathura will not open again. I attached a video. I hope this helps. Might also be some stupid thing just happening on my system

https://github.com/jalvesaq/Nvim-R/assets/7808379/debe33de-8acc-4006-af55-c6dc8ebad6a5

Sincerely
Thomas

P.S. I tried to look into it but vimscript is killing me

**Comment by jalvesaq** [comment] 2023-12-17 21:35
What you want should be achieved with `R_openpdf=2`, but, at least on Wayland, the option no longer works. Please, see: https://github.com/jalvesaq/Nvim-R/issues/783#issuecomment-1853711609

**Comment by jalvesaq** [comment] 2023-12-17 23:07
I made some changes. The issue seems to be fixed on Sway. Maybe it is fixed on the X Server too if the return value of `wmctrl` is different from `0` when it fails to raise a window.

**Comment by jalvesaq** [comment] 2023-12-21 00:02
I believe the issue is fixed. If not, please, reopen it.

**Closed** 2023-12-21 00:01 UTC
