### ISSUE TITLE
No syntax highlighting for python chunks when vim-pandoc-syntax is enabled

### ISSUE THREAD

**Issue by abers** [jalvesaq/Nvim-R#580] opened 2021-03-22 00:49 UTC
Are these two plugins incompatible or is there a setting I need to change in my config?

With vim-pandoc-syntax:
![image](https://user-images.githubusercontent.com/11317054/111927354-57604d80-8aa8-11eb-8081-c7a4d7bdf5d3.png)

Without vim-pandoc-syntax:
![image](https://user-images.githubusercontent.com/11317054/111927326-44e61400-8aa8-11eb-8a32-4b5917d3c372.png)

**Comment by jranke** [comment] 2021-03-22 07:00
For me the combination of Nvim-R and vim-pandoc-syntax works fine, but then I generally do not use python chunks...

**Comment by abers** [comment] 2021-03-22 09:48
Even if I disable all plugins except Nvim-R, vim-pandoc, and vim-pandoc-syntax the issue persists.

My R config is:
```
let g:rmd_fenced_languages = ['r', 'python']
let g:markdown_fenced_languages = ['r', 'python']
```

And my pandoc-syntax config:
```
let g:pandoc#folding#mode = 'syntax'
let g:pandoc#filetypes#handled = ["pandoc", "markdown", "rst"]
let g:pandoc#modules#enabled = ["formatting", "folding", "toc", "command", "menu", "bibliographies", "completion", "keyboard"]
let g:pandoc#folding#fold_yaml=1
let g:pandoc#syntax#codeblocks#embeds#langs = ["python", "r"]
let g:pandoc#biblio#bibs = ["/home/alasdair/zettel/zettel.bib"]
let g:pandoc#syntax#conceal#use = 0
```

**Comment by jalvesaq** [comment] 2021-03-28 15:52
I believe the issue is fixed in [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime). Please, update it (or install it if not installed yet).

**Comment by abers** [comment] 2021-03-28 16:00
Thanks for the reply. I have now installed R-Vim-runtime. It has fixed the code block issue... but I have a new issue whenever I open an RMarkdown file a split is open for `:/// R Language Server` and the buffer with the Rmd file is emptied - losing all it's content. 

![image](https://user-images.githubusercontent.com/11317054/112758546-eb6d7000-8fe6-11eb-838f-6785e4ee05e3.png)

**Comment by jalvesaq** [comment] 2021-03-28 16:06
I can't replicate this new issue. The language server is certainly created by another plugin because neither Nvim-R nor R-Vim-runtime runs a language server.

**Comment by abers** [comment] 2021-03-28 16:29
Ah! My bad - I had installed coc and the coc-r-lsp plugin in the interim between opening this issue and your reply. Adding a path for R binary to the coc-config file solves this issue. All now appears to be working.

I know in the help file it says it is possible to set up Python code completion using jedi-vim - but is it possible to set it up to use coc-pyright instead?

Thanks again!

**Comment by jalvesaq** [comment] 2021-03-28 18:51
You could try jedi-vim + coc-omni.

**Comment by jalvesaq** [comment] 2021-03-30 00:52
> I know in the help file it says it is possible to set up Python code completion using jedi-vim - but is it possible to set it up to use coc-pyright instead?

No, because, as far as I know, coc doesn't use the default omni completion system. What Nvim-R omni completion does in Rmd files is:

 - If inside an R chunk, run R completion
 - Otherwise, if inside Python chunk, call jedi-completion
 - Otherwise, if has a bib file, call RCompleteBib
 - Otherwise, if zotcite is installed, call zotcite#CompleteBib
 - Otherwise, if pandoc is installed, call pandoc#completion#Complete

**Comment by jalvesaq** [comment] 2021-03-31 01:19
I'm closing the issue because what was originally reported is fixed, and I can't fix the coc completion. Indeed it would be good to have a coc source that completed code in RMarkdown in a way similar to that of Nvim-R (the completion being dependent on what part of the code the cursor is in).

**Closed** 2021-03-31 01:19 UTC
