### ISSUE TITLE
Feature Request: add option to skip `eval = FALSE` chunks in Rmarkdown

### ISSUE THREAD

**Issue by zkamvar** [jalvesaq/Nvim-R#413] opened 2019-06-12 10:04 UTC
I usually build RMarkdown documents for instructional purposes, but often run into errors because we will often have demonstrative chunks that are not supposed to be evaluated (e.g. function calls with missing arguments for the student to fill). 

Is it possible to include a new type of `RSendChunkFH` that would ignore chunks where `eval = FALSE`?

**Comment by jalvesaq** [comment] 2019-06-16 18:40
Thanks for reporting the issue!
Ignoring chunks with `eval=FALSE` is the correct behavior and what you report is a bug to be fixed. I think that we even don't need an option for this.

**Comment by jalvesaq** [comment] 2019-06-19 11:33
I believe the issue is going to be fixed by the next commit. If not, please reopen the issue.

**Closed** 2019-06-19 11:34 UTC

**Comment by zkamvar** [comment] 2019-06-19 12:59
Can confirm that it works with this test:

````r

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# toggle to render full version 
full_version   <- FALSE
render_snippet <- if (full_version) 'asis' else FALSE
```


```{r test1,eval=FALSE}
stop('should not stop')
```

```{r test2}
print(pi)
```

````


Output:

```r
NvimR.chunk()
3.141593
```
