### ISSUE TITLE
(NFA) Could not pop the stack

### ISSUE THREAD

**Issue by gwd999** [jalvesaq/Nvim-R#581] opened 2021-03-24 13:40 UTC
Hi thanks for this aweseome plugin 

II am currently trying to start up the plugin with Neovim v0.4.4. 
on a Windows 10 Enterprise edition machine  ... 
I have been playing around quite a bit with the R path etc settings 
BUT I am stuck now with 
```Error detected while processing function UpdatePathForR 
  line 8 
  E874:  (NFA) Could not pop the stack 
  line 10 
  E874:  (NFA) Could not pop the stack 
  ``` 
I think/hope that this is not a big deal ... 
Any ideas where I should change-tewak something on such an error_ 
Thanks

**Comment by jalvesaq** [comment] 2021-03-24 17:28
I don't have spare time to check this on Windows. But could you try replacing line 791 of R/common_global.vim:

```
        if $PATH !~ '^' . g:rplugin.R_path
```

with:

```
        if substitute($PATH, '\\', '/', 'g') !~ '^' . g:rplugin.R_path
```
?

Does it work?

**Comment by gwd999** [comment] 2021-03-24 19:27
Will check yr suggestion tomorrow -> afaict since I have started digging deeper into the issue; it started of with some quirks that were proxy/firewall related - since I have some experience with these I did not worry too much. 
But I decided to implement Nvim-R + Neovim on my WINDOWS 10 host at home as well, Nvim-R runs like a charm on my Ubuntu 20.04 in WSL2; 
BUT the topic seems to be a tougher one based within WINdows toolchain and R pkg builds (looks Nvim-R is not alone - for example ['rextender'](https://github.com/extendr/rextendr/blob/main/vignettes/setting_up_rust.Rmd) [eg libR-sys](https://github.com/extendr/libR-sys/#windows-specific-instructions) [R and Rust integration] seem to have similar issues with the MSVC and GCC toolchains getting in each others way on Windows). As far as I can tell the current troubles are originating in the  `... bin/ld.exe: cannot find -lmsvcrt`  resulting in `[Makefile.win:10: nclientserver.exe] Error 1` 
If your `common_global.vim` modification does not do the trick, I will have a better look at the end of the week.  
Thanks for your swift reply ... 
stay home stay safe.

**Comment by jalvesaq** [comment] 2021-03-24 19:45
NFA is the Vim/Neovim engine for dealing with string patterns in regular expressions. Windows uses backslashes instead of forwarding slashes, and backslashes indicate that the following character has a special meaning, such as `\n` meaning "new line".

**Comment by gwd999** [comment] 2021-03-27 11:18
> Does it work? 
` if substitute($PATH, '\\', '/', 'g') !~ '^' . g:rplugin.R_path`
fixed it on my "home" machine ... will check my other device after the weekend 
Thanx!

**Comment by gwd999** [comment] 2021-03-27 21:18
Hi I have looked into your code base a little bit further and I tripped over a piece of code I do not fully comprehend - I have to warn you upfront that I have never touched vimscript before! 

In file  `setcompldir.vim`  somewhere between  lines 16 and 44 there are to `if` blocks  
    
one beginning with    
`if executable('whoami') ... ` 


and the other one beginning with 
`if g:rplugin.userlogin == ""  ... `

the first block based on the comment preceding it handles potential Domains in Windows logins .... 

Now my question, during (simple) monitoring of these if blocks I have noticed, that the second will regularly get executed twice, while the first one  will usually successfully execute the `whoami` and despite there being a `$USERNAME` [which I just printed out by inserting `call RWarningsMsg("USERNAME = " . $USERNAME) ` just one leine before  the returned message `Could not determine username` which is then followed by ` let g:rplugin.failed = 1`

What do you thin - could there be some flaw in these two control statements, or am I missing something?

**Comment by jalvesaq** [comment] 2021-03-27 22:22
I'm going to remove the superfluous code from `setcompldir.vim`, but I couldn't replicate the bug in the virtual machine. So, I'm not going to fix the bug that you reported in your last comment.

**Comment by gwd666** [comment] 2021-03-27 22:47
> I'm going to remove the superfluous code from `setcompldir.vim`, but I couldn't replicate the bug in the virtual machine. So, I'm not going to fix the bug that you reported in your last comment.

Don't panic ;-) this is me [gwd999] again just with my "JOB alter ego github username" 
All fine with me -> what is extremely "weird" is that  I can also not reproduce it on my "HOME " machine? 
BUT what has come to my attention is that the version seems to differ heavon the two PCs. 
the installation on my job PC is showing itself as master (so I guess dev) and NOT stable branch BUT there is simply no method I can apply to force vim-plug to fetch the stable and not the master branch.  I have also tried cloning from the command line to no avail. mabe it is a firewall issue I ran into dunno ...

**Comment by jalvesaq** [comment] 2021-03-27 22:54
My tests are with the master branch. With Vim-plug, you can switch between branches in this way:

```
Plug 'jalvesaq/Nvim-R' { 'branch': 'stable'}
```

**Comment by gwd666** [comment] 2021-03-27 23:08
> My tests are with the master branch. With Vim-plug, you can switch between branches in this way:
> 
> ```
> Plug 'jalvesaq/Nvim-R' { 'branch': 'stable'}
> ```

I know - I have exactly this line (or command) in my init.vim [ven copy/pasted it because I no longer believed in my typing :-) ] but in the end I had to "manually" checkout the "stable" branch  in Git Bash to "force" the switch ... BUT still/again throws  me same "Could not determine  user name." warnings ... 
very awkward 

![image](https://user-images.githubusercontent.com/57595487/112737296-bebf4700-8f59-11eb-9ff3-edac92585fb5.png)

**Comment by jalvesaq** [comment] 2021-03-28 01:59
Are these errors from the "stable" branch? I'm very busy in my real job to find spare time to maintain even the master branch and, unfortunately, I have absolutely no time to fix bugs in the stable branch. So, the best thing to do is to delete it.

**Comment by jalvesaq** [comment] 2021-03-28 12:30
A comma is missing from the line that I wrote as an example:

```
Plug 'jalvesaq/Nvim-R', { 'branch': 'stable'}
```

**Comment by jalvesaq** [comment] 2021-03-28 12:36
> very awkward

I suggest that you completely delete all config directories and start with a minimal `init.vim`.

> I had to "manually" checkout the "stable" branch in Git Bash to "force" the switch

Also, completely delete the vim-plug directory and let vim-plug install the plugins.

**Comment by jalvesaq** [comment] 2021-03-31 01:22
I'm closing the issue because what was originally reported seems to be fixed. Please, reopen the issue if it is not fixed or report a new issue if necessary.

**Closed by jalvesaq** 2021-03-31 01:22 UTC
