### ISSUE TITLE
Tmux no longer being spawned, getting R inside of a vim buffer instead

### ISSUE THREAD

**Issue by slagtermaarten** [jalvesaq/Nvim-R#618] opened 2021-09-06 10:29 UTC
Hi, 
Thanks first and foremost for maintaining this super useful package.
I recently updated my vim packages and now notice new R sessions are no longer being spawned in new tmux panes, but in new vim buffers instead. I haven't altered my vim settings at all since this 'break' occurred. Is this the end of tmux support of the master branch? Or can I still get it to work somehow? 
Kind regards, Maarten

**Comment by jalvesaq** [comment] 2021-09-06 10:51
Maybe this is a duplicate of https://github.com/jalvesaq/Nvim-R/issues/474

**Comment by slagtermaarten** [comment] 2021-09-06 13:48
Hi, thanks, it's not. I had already implemented the changes suggested in the linked article.

**Comment by jalvesaq** [comment] 2021-09-06 14:04
I can't replicate the issue. Although I'm no longer maintaining the code it still works with both Vim and Neovim:

```vim
let R_in_buffer = 0
let R_source = '/path/to/Nvim-R/R/tmux_split.vim'
```

**Comment by slagtermaarten** [comment] 2021-09-07 04:08
Hmm that's weird, it doesn't work for me anymore and I don't recall changing anything related. The buffer based version seems to work for me as well, I'll work like this for a while. Thanks..!

**Closed** 2022-09-18 01:17 UTC
