### ISSUE TITLE
terminal width is not updated (leading to truncation of output)

### ISSUE THREAD

**Issue by idavydov** [jalvesaq/Nvim-R#758] opened 2023-09-29 14:52 UTC
Hi,

Thanks for the great package.

I have line numbers enabled in the buffer. When the number of rows is increasing beyond 100, the terminal width changes. But nvim-R doesn't seem to update `options(width = ...)`. Do you think this is something which can be fixed on the side of Nvim-R?

Here's how to reproduce the issue:

- Open R file
- Start R `\rf`
- Run the following code
```r
paste(rep("\n", 100)) |> cat()
rep(letters, 3) |> paste(collapse = "")
```

One of the alphabet letter is invisible.

![2023-09-29_16-48-58 (1)](https://github.com/jamespeapen/Nvim-R/assets/671660/7d933516-daa6-458c-beb9-897c7fcd3cdd)

<sub>(incorrectly opened a ticket in jamespeapen/Nvim-R#7)</sub>

**Comment by jalvesaq** [comment] 2023-09-30 10:31
Whether R's option 'width' is correct or not, Neovim should render the output correctly. If the option was incorrect, you should see R breaking vectors in commands such as `rnorm(200)` at the wrong places while printing them.

Anyway, I can't replicate the issue, but, looking at Nvim-R's code, I noted that the option 'numbers' was being checked before `R_buffer_opts` was executed and I fixed this bug. I had to set `R_buffer_opts` as "number" to try to replicate the issue that you reported.

**Comment by idavydov** [comment] 2023-10-02 09:10
Thanks, @jalvesaq .

Unfortunately that didn't fix the issue. However, I noticed that it has something to do with `Heirline.nvim`. If I disable it, I cannot reproduce the issue anymore.

I will try to see which part of heirline configuration is causing this.

**Comment by jalvesaq** [comment] 2023-10-02 09:49
Since the problem is being caused by another plugin, I will close this issue...

**Closed by jalvesaq** 2023-10-02 09:49 UTC
