### ISSUE TITLE
Error detected while processing function StartR

### ISSUE THREAD

**Issue by stephematician** [jalvesaq/Nvim-R#496] opened 2020-05-31 03:21 UTC
Using Vim 8.2 (Ubuntu 18.04), and Nvim-R_0.9.13 (latest release); I get the following error upon \rf

    Error detected while processing function StartR[17]..CheckNvimcomVersion[65]..IsDirWritable:
    line   13:
    E654: missing delimiter after search pattern: 482
    Error detected while processing function StartR[17]..CheckNvimcomVersion:
    line   65:
    E171: Missing :endif
    Error detected while processing function StartR:
    line   17:
    E171: Missing :endif

**Comment by jalvesaq** [comment] 2020-05-31 11:54
The issue is fixed in the development version (this repository). I can't fix issues in released versions, and I can't release a new version now because there are some changes that still need to be tested (use of float windows during omnicompletion and support for debugging functions). If there is no bug report in the next few days, I will release a new version of Nvim-R soon.

Anyway, this bug should happen only in Neovim on Windows because the condition `has("nvim") && has("win32")` should be true to the line 13 of `IsDirWritable` be reached.

**Comment by jalvesaq** [comment] 2020-06-02 01:57
I released a new version of Nvim-R, and now there is a `stable` branch. So, please, update the plugin and report any error that you find.

**Closed by jalvesaq** 2020-06-02 01:57 UTC
