### ISSUE TITLE
Nvim-R hanging for seconds while calling GetRArgs()

### ISSUE THREAD

**Issue by n0542344** [jalvesaq/Nvim-R#526] opened 2020-08-05 15:25 UTC
Thanks a lot for the awesome `Nvim-R` package, it's incredible use- and powerful!  Never the less I'm experiencing some issues and I assume `Nvim-R` is the cause, more precisely the call of the `GetRArgs()`-function.

I'm using `Nvim-R` on several different machines running Linux (`Fedora 32`, `Debian 10` (actually `PureOS 9.0 Amber`), `Arch Linux` (actually `Parabola`) and `openSUSE Leap 15.1`) on different computers (from very slow Athlon II processors with 4GB of memory to servers with 12 cores and 250GB of memory) with different versions of `neovim` (`0.3.4` on `Debian`, `0.3.7` on `Fedora` and `0.4.3` on `Arch`).  I have the most recent version of `Nvim-R` installed (hash `dd27290`) via the `Packager` plugin manager.

In all of those situations I'm experiencing the strange behavior that sometimes (often after using `nvim` for more than several minutes) `nvim` freezes for several seconds when changing a word and going into insert mode.  This behavior is not consistent, sometimes it happens often, sometimes not for more than an hour or two.

Since my `init.vim` is huge and I'm using a multitude of plugins, I tried to discover the source of the issue. By using the profiler in `nvim` via

    :profiler start profile.log
    :profiler func *
    :profiler file *

and looking into the summary at the end I was able to discover the following:

    FUNCTIONS SORTED ON SELF TIME
    count    total (s)    self (s)    function
    2        6.213310     6.101297    GetRArgs()
    ....

The next-slowest functions are far behind (with a time on self below 0.2 seconds). This is also consistent with my subjective experience for that specific session because after starting the profiler `nvim` froze twice for approx. 5 seconds before I closed it.

Has anybody experienced that as well? Do you have any idea how this issue could be resolved? Can I provide you with any additional information?

Thanks a lot, best wishes, 
Alex (life science PhD-student from Vienna, Austria)

---

Edit: corrected version number of neovim on Arch

**Comment by n0542344** [comment] 2020-08-06 07:45
I'm unsure if it helps, but I can also post the output of the `nvim profiler`:

    FUNCTION  GetRArgs()
    Called 2 times
    Total time:   6.213310
     Self time:   6.101297
    
    count  total (s)   self (s)
        2              0.000006     if string(g:SendCmdToR) == "function('SendCmdToR_fake')"
                                        return []
                                    endif
                                
        2              0.000006     let msg = 'nvimcom:::nvim_complete_args("' . a:rkeyword0 . '", "' . a:base . '"'
        2              0.000002     if a:firstobj != ""
                                        let msg .= ', firstobj = "' . a:firstobj . '"'
                                    elseif a:pkg != ""
        2              0.000004         let msg .= ', pkg = ' . a:pkg
        2              0.000001     endif
        2              0.000003     let msg .= ', extrainfo = TRUE)'
                                
                                    " Save documentation of arguments to be used by nclientserver
        2              0.000043     call delete(g:rplugin.tmpdir . "/args_for_completion")
        2              0.000004     let s:ArgCompletionFinished = 0
        2   0.000110   0.000014     call SendToNvimcom("\x08" . $NVIMR_ID . msg)
                                
        2              0.000003     let ii = 200
      204              0.002121     while ii > 0 && s:ArgCompletionFinished == 0
      202              0.001360         let ii = ii - 1
      202   6.095523   6.095296         sleep 30m
      202              0.001776     endwhile
                                
        2              0.000008     if s:ArgCompletionFinished == 0 && ii == 0
        1              0.000004         return []
                                    endif
                                
        1              0.000009     if exists('s:compl_menu')
        1              0.000309         unlet s:compl_menu
        1              0.000001     endif
        1              0.000003     let s:waiting_compl_menu = 1
        1   0.000096   0.000074     call JobStdin(g:rplugin.jobs["ClientServer"], "5A" . a:base . "\002" . a:rkeyword0 . "\n")
        1   0.111678   0.000010     return WaitRCompletion()

If you need anything else don't hesitate to ask for it!

Best wishes, 
Alex

**Comment by jalvesaq** [comment] 2020-08-16 00:41
Thanks for all the info! There are two issues here.

1. The waiting time to get the arguments should not be so long. This is an annoyance.
2. Nvim-R shouldn't fail to get the function arguments. This is a bug.

I decreased the waiting time, but, unfortunately, I don't have time to investigate the real bug now.

**Comment by jalvesaq** [comment] 2020-08-16 00:47
If you are using a plugin to enable automatic omnicompletion while you type, be sure to have "noinsert" as part of the 'completeopt' option. This should prevent Nvim-R from trying to get extra info on objects being completed.

**Comment by jalvesaq** [comment] 2020-09-19 12:38
Maybe this issue was being caused by a bug that is now fixed: https://github.com/jalvesaq/Nvim-R/issues/535

**Comment by jalvesaq** [comment] 2021-03-30 01:27
Please, reopen the issue if it still not fixed.

**Closed by jalvesaq** 2021-03-30 01:27 UTC
