### ISSUE TITLE
`let R_assign_map = '<M-->'` does not work to me

### ISSUE THREAD

**Issue by iago-pssjd** [jalvesaq/Nvim-R#634] opened 2021-11-18 10:21 UTC
Following the [documentation](https://github.com/jamespeapen/Nvim-R/wiki/Options#assignment-operator-and-rnoweb-completion-of-code-block), I have added
```
set <M-->=^[-
let R_assign_map = '<M-->'
```
to `~/.vimrc` in order to use `Alt--` to insert `<-` but it is not working (it just avoids replacing `_` by `<-`). It places the cursor at the beginning of one line up. I looked for
```
:verbose map ^[-
```
to see if it was used for another plugin, but I get `No mapping found`. Which can be the issue?

Thanks!

**Comment by jalvesaq** [comment] 2021-11-18 11:41
A can replicate the issue. If I do the trick taught at [stackexchange](https://vi.stackexchange.com/questions/2350/how-to-map-alt-key) (answer 69), I find `-` as the final string of `<M-->`. However, without, any trick, that is, without using the `sed -n l` command, if I hold the left `Alt` key and press `=` in Insert mode, I get `½`. So, I put in my `init.vim`:

```
let R_assign_map = '½'
```

and now I can press <key>Alt</key><key>=</key> to get " <- ". I was still using the default underscore as `R_assign_map`, but I liked so much the `<M-=>` that now I switched to it.

Maybe someone else can find a way of mapping `<M-->`...

Thanks for reporting the issue!

**Comment by mschilli87** [comment] 2021-11-19 07:36
@jalvesaq:
> ... if I hold the left Alt key and press = in Insert mode, I get ½.

If I do the same, I am taken to normal mode (neovim 0.4.4, `us` layout).

**Comment by jalvesaq** [comment] 2021-11-19 21:33
My keyboard has the Brazilian layout. The keys are mostly in the same position as in the U.S. keyboard, but it seems that we have more variation in the output of Alt keys.

**Comment by jalvesaq** [comment] 2022-11-01 01:52
I'm closing the issue because the problem is fixed in Neovim: `let R_assign_map = '<M-->'` works as expected.
I don't know when it was fixed... I'm using Neovim v0.9.0-dev.

**Closed by jalvesaq** 2022-11-01 01:52 UTC

**Comment by iago-pssjd** [comment] 2022-11-02 16:12
Not working yet with ViM 8.2 on Debian stable :(

**Comment by jalvesaq** [comment] 2022-11-02 18:21
It does not work with Vim, only with GVim and Neovim. But it is a limitation of Vim, not Nvim-R.

**Comment by iago-pssjd** [comment] 2022-11-03 06:01
Do you mean this will not work even with future versions of ViM?

**Comment by jalvesaq** [comment] 2022-11-03 11:19
I don't know because I'm not part of Vim's development team, but similar issues have already been reported:
https://github.com/vim/vim/issues?q=is%3Aissue+is%3Aopen+map+alt+key+
