### ISSUE TITLE
setting R_clear_line=1 prevents neovim R terminal window from closing after quiting R

### ISSUE THREAD

**Issue by songcai** [jalvesaq/Nvim-R#368] opened 2018-10-24 16:29 UTC
Hi Jose,
I am using the latest Nvim-R with Neovim. I have the following options in .vimrc
  let R_in_buffer = 1
  let R_close_term = 1
  let R_clear_line = 1
I know that the first two options are default and necessary. I am just showing you that I am using the Neovim built-in terminal for R. When I have R_clear_line = 1, if I quit R using \rq, the Neovim R terminal window does not close. When I set R_clear_line = 0, the R terminal window closes as expected if I use \rq.

Please fix the issue.

Best,
-Song

**Comment by jalvesaq** [comment] 2018-10-29 01:00
`R_clear_line` does not work at all for me (Ubuntu 18.10). I see `^A^K` in the R buffer.

**Comment by songcai** [comment] 2018-10-29 01:57
Hi Jackson,

There are a few possible reasons for that as follows.
  (1)  ^A^K is a shortcut from GNU Readline library. To use that key combination, you have to make sure that the related software (e.g. Neovim/Vim, R, and Tmux if you use it) are built with Readline library. By default, they all are.
  (2) In ~/.inputrc, if you set the editing mode as "vi" mode, then this key combination won't work (this is described in the Nvim-R document). It also may not work if you set "vi" mode in ~/.bashrc.
  (3) If you use Tmux, and set the prefix for Tmux as "C-a" in ~/.tmux.conf, then the key combination won't work in Tmux. This is described in the Nvim-R documentation as "However, sending <C-a> may be problematic if using Tmux". I think it is better to update the documentation to give the exact reason.

I cannot think of other reasons. The key is to ensure that Realine is in effect and it's default key combinations are not changed (for example, to "vi" mode).

For the original question, I think <C-a><C-k> is interacting with Neovim somehow, which prevents Neovim terminal from closing. Could you please tell me which are the source files to send <C-a><C-k>, to implement \rq, and to close Neovim terminal window after R exits? I maybe able to figure something out after knowing those.
-Song

**Comment by songcai** [comment] 2018-12-29 20:40
A solution has been found.

A simple fix is to change line 66 of nvimbuffer.vim from
`call feedkeys('<cr>')`
to
`call feedkeys('a ')`

A better but a little lengthier fix is to replace line 66 of nvimbuffer.vim
`call feedkeys('<cr>')`
by
`
if match(getline('.'), 'make: \*\*\* \[[^\]]\+] Error ') == -1
    call feedkeys('a ')
 endif
`
This way, if there is an error message, the terminal will not close. Note that this fix is adapted from https://www.reddit.com/r/neovim/comments/7xonzm/how_to_close_a_terminal_buffer_automatically_if/.

Jakson: could you please implement one of the above fixes?

**Comment by jalvesaq** [comment] 2018-12-29 23:20
With `call feedkeys('a ')` I get the message "Did you already start R?", but `call feedkeys(' ')` seems to work fine. Could you confirm, please?

The pattern `'make: \*\*\* \[[^\]]\+] Error '` would be useful only if running `make`, not `R`.

**Comment by songcai** [comment] 2018-12-30 02:37
Strangely, `call feedkeys(' ')` behaves the same as `call feedkeys('<cr>')` for me, i.e., it does not close the terminal buffer. `call feedkeys('a ')` works perfectly for me, without giving any message.

**Comment by songcai** [comment] 2018-12-30 18:21
I digged a little and found the reason of using two letters as feedkeys.

The feedkeys have to be at least two keys. The purpose of the first key is to enter the insert mode, so 'a' or 'i' will work but the others won't. The purpose of the second key is to press any key after entering insert mode, which is how Neovim close a buffer after the shell exits. Hence, any key as the second key will work. One can add extra keys, but those won't be in effect.

For example, 'a ', 'a<cr>', 'abb c', 'i ', and 'icc' will all work because the first key is either 'a' or 'i' and the string is at least two-keys long.

However, 'ca', 'ba', '<cr>a', ' ', and '<cr>' won't work because they do not satisfy the above rules.

I tested the above on macOS Mojave and a Debian Linux server with kernel 3.10.0. The above rules work on both OSes. I do not have an up-to-date Linux to try them out though.

As for the message "Did you already start R?" that you got (which I never get), it might be related to other things. After calling R, I found that I should wait a second or so then send commands. What if you wait for a second then send some other command like `ls()` then quit R with `\rq`? Do you still have that message?

**Comment by jalvesaq** [comment] 2019-01-01 13:52
> Does "^A^K" work in a terminal emulator? If yes, than I do not know. I do not have this problem.

No, it doesn't. I compiled R from source, and maybe something is missing in my setup.

**Comment by songcai** [comment] 2019-01-01 15:07
If I understand correctly, when you open an terminal emulator (not running R) and type in something like "asdfadfaf" then type ^A^K, the string "asdfadfaf" does not get deleted?

If this is the case, this is not a problem about R, but a problem about Readline library. Please see my third post on Oct 28, 2018.

If what you described happens in an R console (a terminal running R), then it is most likely that you did not compile R with Readline library.

**Comment by songcai** [comment] 2019-01-01 15:10
By default R compiles with readline library. The option for this is "--with-readline=yes" when using make.

**Comment by jalvesaq** [comment] 2019-01-01 15:59
Thanks for the comments! After some tests, I discovered that `R_clear_line` wasn't working because I had this in my `~/.bashrc`:

```
set -o vi
```

**Comment by songcai** [comment] 2019-01-01 16:03
Here you go!

**Comment by jalvesaq** [comment] 2019-01-01 17:20
I added a new option, `R_editing_mode`, and I believe the issue is fixed now. It would be better if I could query either readline or R on what is its current editing mode to dynamically define the value of `R_editing_mode`.

**Comment by songcai** [comment] 2019-01-01 17:30
Great idea to add R_editing_mode. It works for Neovim flawlessly. However it does not work for Vim or MacVim. I guess you need to add the option for Vim and MacVim separately.

**Comment by songcai** [comment] 2019-01-01 17:42
Having vi mode in .inputrc with R_editing_mode=1 does fix clear line issue, but has side effect for other commands that use readline. For example \rr sends ^L to clear screen, but with vi mode in .inputrc this won't work.

It would be great if R_editing_mode can work for all commands that use readline.

**Comment by jalvesaq** [comment] 2019-01-01 17:58
Is there a vi command to clear the screen?

I have only found a way of telling readline to clear the screen with CTRL-L. Please, see https://unix.stackexchange.com/questions/104094/is-there-any-way-to-enable-ctrll-to-clear-screen-when-set-o-vi-is-set

**Comment by songcai** [comment] 2019-01-01 20:07
> Is there a vi command to clear the screen?
> 
> I have only found a way of telling readline to clear the screen with CTRL-L. Please, see https://unix.stackexchange.com/questions/104094/is-there-any-way-to-enable-ctrll-to-clear-screen-when-set-o-vi-is-set

I do not know of other ways. The question is: is there any other nvim-r command using readline? If so, they all have to be dealt with.

**Comment by jalvesaq** [comment] 2019-01-01 20:11
> is there any other nvim-r command using readline?

I only remember these two: clean line and clear screen.

**Comment by songcai** [comment] 2019-01-01 20:20
I confirm that R_editing_mode now works for Vim/MacVim.

I also confirm that enabling vi mode in .inputrc with the trick given in https://unix.stackexchange.com/questions/104094/is-there-any-way-to-enable-ctrll-to-clear-screen-when-set-o-vi-is-set works. That is, adding
`set editing-mode vi
$if mode=vi

set keymap vi-command
# these are for vi-command mode
Control-l: clear-screen

set keymap vi-insert
# these are for vi-insert mode
Control-l: clear-screen 
$endif`
in ~/.inputrc, and adding
`R_editing_mode="vi"`
in ~/.vimrc solve all issues.

Shall I close the issue?

Thanks!

**Comment by jalvesaq** [comment] 2019-01-01 23:04
> Shall I close the issue?

Yes, I guess we can't do anything else. Thanks!

**Closed** 2019-01-02 02:59 UTC
