### ISSUE TITLE
Sending non-ASCII characters to R Console on Windows 10

### ISSUE THREAD

**Issue by wngrtn** [jalvesaq/Nvim-R#125] opened 2016-11-17 11:03 UTC
Can I send non-ASCII characters from vim to R Console on Windows 10? With the default configuration (on a German Windows 10 system), non-ASCII characters get messed up in transit. For example, sending

    x <- '€'
    y <- 'ä'

results in

    x <- 'â‚¬'
    y <- 'Ã¤'

**Comment by jalvesaq** [comment] 2016-11-17 23:25
I really don't use Windows, but I think you should look at:
```vim
:h encoding
:h fileencoding
```

**Comment by wngrtn** [comment] 2016-11-18 17:17
Thank you for pointing me in the right direction.

Text arrives in R Console unsrambled if I `set encoding=latin1` in vim, but it doesn't seem to be possible to set a utf-8 locale in R under Windows.

Since `set encoding=latin1` breaks several other things in vim, most notably the patched fonts used by vim-airline, this is not really an option.

Would it be possible for me to patch Nvim-R and insert a conditional character conversion on Windows? Where would I put that code?

**Comment by jalvesaq** [comment] 2016-11-20 02:11
I don't know what exactly you want to do, but, if you want to set the encoding as Latin1, you could try an autocommand, like:

```vim
autocmd BufNewFile,BufRead *.R set encoding=latin1
```

**Comment by jalvesaq** [comment] 2016-12-02 12:13
I am closing this issue because it is a matter of Vim configuration, not a bug of Nvim-R.

**Closed by jalvesaq** 2016-12-02 12:13 UTC

**Comment by jalvesaq** [comment] 2017-01-24 11:17
Becuse of https://github.com/jalvesaq/Nvim-R/issues/151 I am reading your question again, and, yes, you can patch Nvim-R. See:
```
:h R_source
:h iconv()
```
You have to create and source your own vim script. Its contents would be (not tested):
```vim
function! SendCmdToR_Windows(...)
    if g:R_ca_ck
        let cmd = "\001" . "\013" . a:1 . "\n"
    else
        let cmd = a:1 . "\n"
    endif
    let cmd = iconv(cmd, "UTF-8", "latin1")
    call JobStdin(g:rplugin_jobs["ClientServer"], "\003" . cmd)
    return 1
endfunction
```
Then, you would put in your vimrc:
```vim
let R_source = "/path/to/your/script.vim"
```

**Comment by wngrtn** [comment] 2017-01-24 18:49
Thanks a lot! I had to replace `latin1` with `windows-1252` and `let R_source` with `let g:R_source` but now it works like a charm. Users with Windows systems that use different default encodings will probably need another encoding instead of `windows-1252`, but this works fine on my German language system.

Here is the corrected code if anyone wants to copy and paste:

```vim
function! SendCmdToR_Windows(...)
    if g:R_ca_ck
        let cmd = "\001" . "\013" . a:1 . "\n"
    else
        let cmd = a:1 . "\n"
    endif
    let cmd = iconv(cmd, "UTF-8", "windows-1252")
    call JobStdin(g:rplugin_jobs["ClientServer"], "\003" . cmd)
    return 1
endfunction
```

```vim
let g:R_source = '~/vimfiles/Nvim-R_unicode_fix_windows.vim'
```

**Comment by jalvesaq** [comment] 2017-01-24 19:22
I am glad to know that the code works well enough for you case, but be careful because wrong characters might be sent to R if a valid UTF-8 string is not representable in the encoding used by R. Example:
```r
cat("The standard deviation, σ, is 0.32\n")
```

**Comment by wngrtn** [comment] 2017-01-24 19:46
True. Thanks for cautioning me about that. I wish there was a way to make R use utf-8 on Windows, but I guess there isn't.

This problem pushed me towards using unicode codes a la `\u00e4`, but on the downside, this make the code much harder to read.
