### ISSUE TITLE
nvimcom installation failed

### ISSUE THREAD

**Issue by FanchCollin** [jalvesaq/Nvim-R#59] opened 2016-04-18 15:18 UTC
OS: GNU/Linux Debian Jessie - Nvim-R.0.9.3

The installation of nvimcom failed because rewritable directory (/usr/...). I solved it by a build of the nvimcom package using the sources (R CMD BUILD nvimcom) and installed it from the R (install.packages(...)). 

PS: Nvim-R plugin is really a good job, bravo!

**Comment by jalvesaq** [comment] 2016-04-19 09:51
I thought this was fixed by https://github.com/jalvesaq/Nvim-R/commit/20cad6caccada0d5d984b2ca18ec22304a983c62 which was the last commit before the release of Nvim-R_0.9.3.

**Comment by NikosAlexandris** [comment] 2016-04-20 12:17
I have the following vim compiled from source

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 20 2016 12:56:43)
Included patches: 1-1753
Compiled by nik@gridgisOne
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     -tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save                                                                                                                                                                                     
+ex_extra        -mouse_gpm       -sun_workshop    +xpm                                                                                                                                                                                            
+extra_search    -mouse_jsbterm   +syntax                                                                                                                                                                                                          
   system vimrc file: "$VIM/vimrc"                                                                                                                                                                                                                 
     user vimrc file: "$HOME/.vimrc"                                                                                                                                                                                                               
 2nd user vimrc file: "~/.vim/vimrc"                                                                                                                                                                                                               
      user exrc file: "$HOME/.exrc"                                                                                                                                                                                                                
  system gvimrc file: "$VIM/gvimrc"                                                                                                                                                                                                                
    user gvimrc file: "$HOME/.gvimrc"                                                                                                                                                                                                              
2nd user gvimrc file: "~/.vim/gvimrc"                                                                                                                                                                                                              
    system menu file: "$VIMRUNTIME/menu.vim"                                                                                                                                                                                                       
  fall-back for $VIM: "/usr/local/share/vim"                                                                                                                                                                                                       
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1                                                                                                                                                         
Linking: gcc   -L. -Wl,-z,relro -L/build/ruby2.1-bDDI0O/ruby2.1-2.1.5/debian/lib -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux -ldl       -lruby-2.1 -lpthread -lgmp -ldl -lcrypt -lm
```
I installed Nvim-R via git clone under the `~/.vim/bundle` directory (I use `pathogen`).
I then open an R file with vim and hot `,rf`. The final message, in-vim, is:
```
The package nvimcom wasn't loaded yet.
```

And in the external R "terminal", the message(s) read:
```
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found
```

Any help?

**Comment by jalvesaq** [comment] 2016-04-20 13:08
Vim version is not important in this case, and the bug is supposed to be already fixed (see https://github.com/jalvesaq/Nvim-R/issues/44). The most important error message is the first one, not the last one. What is the output of `:messages`.

**Comment by jalvesaq** [comment] 2016-04-21 14:08
The only possibility that I can see for you not getting any error message while Nvim-R tries to update nvimcom and, then, nvimcom not being built and installed is if you have set the value of `R_app` in your vimrc, and both "R" and the value of `R_app` are executable in your system. That is, nvimcom would be installed in the wrong R library path.

**Comment by NikosAlexandris** [comment] 2016-04-22 13:06
The output of `:messages` is:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"/geo/mapx/map-x-shiny/server.R" 114L, 2472C
Error detected while processing function StartR[116]..StartR_ExternalTerm[63]..WaitNvimcomStart:
line   13:
E118: Too many arguments for function: ROnJobExit
E118: Too many arguments for function: ROnJobExit
The package nvimcom wasn't loaded yet.
```

**Comment by NikosAlexandris** [comment] 2016-04-22 13:16
A few more details:

```
grep -nr R_app /home/nik/.vim/*                                                                                                                                                                                              
/home/nik/.vim/bundle/Nvim-R/R/gui_running.vim:258:        amenu R.Help\ (plugin).Options.Integration\ with\ Apple\ Script :help R_applescript<CR>
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:784:    if g:R_applescript
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:2837:call RSetDefaultValue("g:R_applescript",       0)
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:2936:    let g:R_applescript = 0
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:2939:if has("gui_running") || g:R_applescript || g:R_in_buffer || $TMUX == ""
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:3054:if exists("g:R_app")
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:3055:    let g:rplugin_R = g:R_app
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:3084:        call RWarningMsgInp('"' . g:rplugin_R . '" not found. Fix the value of either R_path or R_app in your vimrc.')
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:3094:if g:R_applescript
/home/nik/.vim/bundle/Nvim-R/R/common_global.vim:3098:if !has("win32") && !g:R_applescript && !g:R_in_buffer
/home/nik/.vim/bundle/Nvim-R/R/osx.vim:23:        call RWarningMsg('R.app does not support command line arguments. To pass "' . args_str . '" to R, you must put "let R_applescript = 0" in your vimrc to run R in a terminal emulator.')
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:817:|R_app|               Name of R application
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:829:|R_applescript|       Use osascript in Mac OS X to run R.app
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:1165:                                                                     *R_app*
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:1181:By default the value of `R_app` is `"R"` on Unix systems (such as Linux and
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:1184:should set the value of `R_app` in your |vimrc|.
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:1321:                                                              *R_applescript*
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:1328:   let R_applescript = 1
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:2514:   let R_applescript = 0
/home/nik/.vim/bundle/Nvim-R/doc/Nvim-R.txt:2698: * New option: R_app.
```

and

```
whereis R
R: /usr/bin/R /usr/lib/R /etc/R /usr/local/lib/R /usr/share/R /usr/share/man/man1/R.1.gz
```

while `nvimcom` is in

```
locate nvimcom |grep usr
/usr/local/lib/R/site-library/nvimcom
..
```

`/usr/local`  vs.  the `/usr/lib` is, I guess, related to the problem.

**Comment by NikosAlexandris** [comment] 2016-04-22 14:55
All right. Inside the directory I am launching R, there is indeed an `.Rprofile` which sources another file file `init.R` which, in turn, sets up a packrat project.  I guess this manipulates the path(s).  So, `nvimcom` is loaded just fine while opening and editing another R file, outside of this directory.

**Comment by jalvesaq** [comment] 2016-04-25 18:26
I could reproduce the issue by creating a .Rprofile in the R script directory and adding the following line to it:
```
options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods"))
```
However, I don't know how to fix the bug. Hence, I simply improved the warning message that appears in this case: https://github.com/jalvesaq/Nvim-R/commit/8f4cb7720db9983a751f472c7fd28a838dbf89cb

**Comment by NikosAlexandris** [comment] 2016-04-26 08:41
Adding `nvimcom` to the Packrat project may be one solution (?), using its `external.packages` option or its `packrat::extlib()` utility.

**Comment by jalvesaq** [comment] 2016-04-26 08:55
In the plugin's documentation, I suggest the following:
```
if(Sys.getenv("NVIMR_TMPDIR") == ""){
    options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods"))
} else {
    options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))
}
```
There is no harm in loading nvimcom and not using it, but if people who do not use Vim use your project they will be compelled to install a package that is unnecessary for them.

**Comment by NikosAlexandris** [comment] 2016-04-26 13:54
Meant is to introduce these instructions in the project's `.Rprofile`, right? It does not work for me.

In launching R, both `options("defaultPackages")` and `Sys.getenv("NVIMR_TMPDIR")` confirm no presence of `nvimcom`, of course.  Opening an R file with vim, the previous commands verify the presence of `nvimcom`, as expected.

I test the following: a fresh clone of the project, which is set up with packrat, and introduce the above instructions inside the "local" `.Rprofile`. Then, opening an R file, hitting `,rf` and the project calls the local `.Rprofile`, I guess.

The (improved since the last commit) message still reads: `The package nvimcom wasn't loaded yet. Please, see  :h nvimcom-not-loaded`. The subsequent call to https://github.com/fxi/map-x-shiny/blob/master/.Rprofile#L2 begins to install the required packages.

Same happens without the test for the temporary directory, i.e., forcing
`options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))`.

Maybe some useful information here: https://groups.google.com/forum/#!searchin/packrat-discuss/defaultPackages/packrat-discuss/DXCsGaqKUBM/LG8YhfA_ZPIJ.

**Comment by jalvesaq** [comment] 2016-04-26 14:22
Sorry, but I don't know how to fix the issue. I don't know what exactly packrat is, but I guess that it should do what Nvim-R does: append its dependencies to `R_DEFAULT_PACKAGES` instead of ignoring it. If someone knows how to fix this issue in Nvim-R, a pull request is welcome.

**Comment by NikosAlexandris** [comment] 2016-04-26 15:10
I have some success with
 ```
options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))                            
library(nvimcom)
```

Will report back once I get this cleaned-out.

**Comment by NikosAlexandris** [comment] 2016-04-28 07:33
All right! So many thanks for the suggestion. The following is the/a solution :-)

```
if(Sys.getenv("NVIMR_TMPDIR") == ""){
    options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods"))
} else {
    options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))
    library(nvimcom)
}
```

**Comment by jalvesaq** [comment] 2016-04-28 08:42
Do you really need `library(nvimcom)`? It is already in the `defaultPackages` list. If you do need it, then, the `options()` command is doing nothing, and you don't need it. In this case, you only need this:
```
if(Sys.getenv("NVIMR_TMPDIR") != "")
    library(nvimcom)
```

**Comment by NikosAlexandris** [comment] 2016-04-28 10:01
Right, only `library(nvimcom)` is required. Thanks for the clarification.

**Comment by jalvesaq** [comment] 2016-05-09 08:40
@FanchCollin Is nvimcom still not installing automatically in your system?

**Comment by GordonWiegand** [comment] 2016-05-09 14:28
I have the same problem on OS X 10.11. Sourcing the vim ball always leads to "Error in library(vimcom) : there is no package called ‘vimcom’". I've tried it on a fresh OS with Xquartz 2.7.9 and up to date Xcode, command-line-tools and gcc via homebrew. Other packages install seemless in R.

**Comment by jalvesaq** [comment] 2016-05-09 15:15
@GordonWiegand I did not understand your case because the name of the R package is nvimcom (not vimcom) and the vimball installs Nvim-R for Vim (not nvimcom for R).

You do not have to install nvimcom, and you do not need either `library(vimcom)` or `library(nvimcom)` in your `~/.Rprofile`.

You have only to install Nvim-R in either Vim or Neovim because nvimcom source code is embedded in Nvim-R. Once Nvim-R is installed, nvimcom should be automatically installed the first time that you starts R with the command `<LocalLeader>rf`.

**Comment by GordonWiegand** [comment] 2016-05-12 08:02
Sorry for the delay and the confusion. I don't remember why I've changed .Rprofile in the first place. But now it works. Thank you, and another big thank you for the package. I'm working with it since a couple of years now and it's great.

**Comment by GordonWiegand** [comment] 2016-05-12 09:21
I still have an issue.  `<LocalLeader>rf` evokes R in console (iTerm2) to which I can't send any code afterwards. Any hints?

**Comment by jalvesaq** [comment] 2016-05-12 19:45
I don't have access to a Mac OS X, so I have no suggestion on how to fix the issue with iTerm2.
My suggestion is that you could try Neovim (with R_in_buffer = 1).

**Comment by sesselastronaut** [comment] 2016-05-16 09:42
I just updated the Nvim-R plugin via vundle and now starting R via the `<localleader>rf` returns: 
`Failed to install nvimcom`
`installing to library ‘/usr/local/lib/R/site-library’`
`Error: ERROR: no permission to install to directory ‘/usr/local/lib/R/site-library’`
I've my libraries and the previous nvimcom locally in ~/R/x86_64-pc-linux-gnu-library/3.2/ 
How can I get Nvim-R to put it there?
my .Rprofile looks like this:
```
if(interactive()){
  # Suggested libraries:
  library(colorout)
  library(setwidth)

  # Use text based web browser to navigate through R docs after help.start():
  if(Sys.getenv("NVIMR_TMPDIR") != "")
    library(nvimcom)
    options(browser = function(u) .C("nvimcom_msg_to_nvim",
         paste0('StartTxtBrowser("w3m", "', u, '")')))
}
```

**Comment by jalvesaq** [comment] 2016-05-16 11:35
You don't need `library(nvimcom)` in you .Rprofile anymore, but this was not the cause of the problem.

If you have updated R to version 3.3.0 and did not install any package yet, then, the directory ~/R/x86_64-pc-linux-gnu-library/3.3/ does not exist yet. If indeed this is the problem, I believe it is fixed now: https://github.com/jalvesaq/Nvim-R/commit/9ec08f43384050b6bc0f820661fc89040d9a8ab0

**Comment by sesselastronaut** [comment] 2016-05-16 16:43
Thanks, works now :+1:

**Closed** 2016-05-19 18:16 UTC

**Comment by jonataseduardo** [comment] 2017-01-27 19:42
I had this error also, but I could solve it deleting the old 3.2 R folder.

**Comment by niklaas** [comment] 2017-08-02 07:23
Another solution is to add `nvimcom` to `packrat`'s `external.packages` after installing:

```
packrat::set_opts(external.packages = c("nvimcom"))
```
