### ISSUE TITLE
customizing R comment string not working

### ISSUE THREAD

**Issue by msaidf** [jalvesaq/Nvim-R#49] opened 2016-03-25 19:36 UTC
I think the problem is that in the RComment function, cmt variable is defined as '#', instead of using g:R_rcomment_string like in the RSimpleCommentLine. I am not sure if you intentionally prevent customization of RComment function or there is another way to make the customized comment string working with that setting. In my case, after I change the code to 
`        let cmt = g:R_rcomment_string`
my customized comment string shows up instead of the original #.

**Comment by jalvesaq** [comment] 2016-03-26 00:05
Please, see section 4.5: *Commenting and uncommenting lines*

The behavior of `<LocalLeader>xx` is controlled by `R_indent_commented` and `r_indent_ess_comments`.

`R_rcomment_string` controls `<LocalLeader>xc` and `<LocalLeader>xu`.

Please, tell me if something is not according to the documentation. The first set of options and key binding aims to create some compatibility with Emacs+ESS. The second set of option and key bindings is to meet the needs of other people. We can change either of them, but someone may complain.

**Comment by msaidf** [comment] 2016-03-30 18:49
In the help section 6.12

The string used to comment text with <LocalLeader>xc, <LocalLeader>xu,
> <LocalLeader>xx and <LocalLeader>o is defined by R_rcomment_string.
> Example:
> >   let R_rcomment_string = "# "


So as I understand it, the value of R_rcomment_string should also affect
<localleader>xx, but it does not. But now I know from your email that
R_rcomment_string will only affect the comment made by <localleader>xc and
<localleader>xu. Sure I can use them, but I would prefer to use one keymap
to toggle between commented and uncommented state.

For keeping compatibility with emacs ess, we can keep to use the current ##
and ### if the value of r_indent_ess_comments is 1. For those
setting r_indent_ess_comments =0, I think for consistency the comment
string should follow what is set by R_rcomment_string.

______

Said

**Comment by jalvesaq** [comment] 2016-08-07 16:35
The issue is going to be fixed by the next commit. I hope I did not create any new bug.

**Closed** 2016-08-07 16:36 UTC
